version: 2.1
jobs:
  #Based in part on: https://github.com/ds-102/ds-102-book/blob/master/.circleci/config.yml
  # Push the HTML to the gh-pages branch
  push_html:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      # Install the ghp-import tool
      - run:
          name: "Install ghp-import"
          command: |      
            export PATH=$PATH:/home/circleci/.local/bin
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py --user
            pip install -U ghp-import --user

      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build

      #This will prevent CircleCI trying to build on gh-pages - is there a better way?
      - run: cp -r ./.circleci ./_site

      # Push the `_site` folder to our gh-pages branch
      # The _site folder contains cruft? eg content/ dir?
      - run:
          name: Push site to gh-pages
          command: |
            export PATH=$PATH:/home/circleci/.local/bin
            ghp-import -p -n -f -r https://${GITHUB_PERSONAL_TOKEN}@github.com/ouseful-testing/jupyter-book-autobuild.git _site
  fetch_and_commit:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: create virtualenv
          command: |
            python -m virtualenv env
      - run:
          command: |
            . env/bin/activate
            pip install -r requirements.txt
            pip install ghp-import
      - save_cache: 
          paths:
            - ./env
          key: dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}     
      - run:
          command: |
            . env/bin/activate
            
            jupyter-book create --content-folder content --config _config.yml --overwrite buildbook
            
            jupyter-book toc buildbook
            jupyter-book build buildbook/
            
            cp -r ./.circleci ./buildbook
            ghp-import -p -n -f -r https://${GITHUB_PERSONAL_TOKEN}@github.com/ouseful-testing/jupyter-book-autobuild.git -b jupyterbook buildbook
workflows:
  version: 2
  build:
    jobs:
      - fetch_and_commit:
          filters:
            branches:
              only:
                - master
      - push_html:
          filters:
            branches:
              only:
                - jupyterbook          