name: gh-pages push
on:
  push:
    branches:
    - jupyterbook

jobs:
  gh_pages_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: jupyterbook
    - name: Push build branch gh-pages 
      run: |
        cp -r buildbook/_site /tmp/_site
        git checkout -b gh-pages
        rm -rf *
        mv /tmp/_site/* .
        
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git add --all --force .
        git commit -a --allow-empty-message -m 'Push gh-pages branch'
        git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
        git push --force origin gh-pages 
